name: Test
on:
  push:
    branches-ignore:
      - main
    paths:
      - packages/**

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install and Test
        run: |
          npm ci
          npm run-script build
          cd packages/compas-open-scd
          npm run-script test
